book/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("details/<int:id>", views.DetailBookView.as_view(), name="details_book"),
]

library_management/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import home
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home, name="home"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("accounts/", include("accounts.urls")),
    path("category/", include("category.urls")),
    path("book/", include("book.urls")),
    path("transactions/", include("transactions.urls")),
    path("category/<slug:category_slug>", home, name="category_wise_book"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transactions/urls.py
from django.urls import path
from .views import DepositeMoneyView, TransactionReportView, BorrowBookView
from accounts.views import PasswordChangeView


urlpatterns = [
    path("deposite/", DepositeMoneyView.as_view(), name="deposite_money"),
    path("report/", TransactionReportView.as_view(), name="transaction_report"),
    # path("borrow/", BorrowBookView.as_view(), name="borrow_book"),
    path("borrow/<int:id>/", BorrowBookView.as_view(), name="borrow_book"),
    # path(
    #     "password_change/",
    #     PasswordChangeView.as_view(),
    #     name="password_change",
    # ),
]

transactions/models.py
from django.db import models
from accounts.models import UserLibraryAccount
from .constants import TRANSACTION_TYPE
from book.models import Book

# Create your models here.


class Transaction(models.Model):
    account = models.ForeignKey(
        UserLibraryAccount, related_name="transactions", on_delete=models.CASCADE
    )
    amount = models.DecimalField(decimal_places=2, max_digits=12)
    book = models.ForeignKey(
        Book, related_name="book", on_delete=models.CASCADE, null=True
    )
    balance_after_transaction = models.DecimalField(decimal_places=2, max_digits=12)
    transaction_type = models.IntegerField(choices=TRANSACTION_TYPE, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["timestamp"]

transactions/forms.py
from django import forms
from .models import Transaction
from book.models import Book


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ["amount", "transaction_type"]

    def __init__(self, *args, **kwargs):
        self.account = kwargs.pop("account")
        super().__init__(*args, **kwargs)
        self.fields["transaction_type"].disabled = True
        self.fields["transaction_type"].widget = forms.HiddenInput()

    def save(self, commit=True):
        self.instance.account = self.account
        self.instance.balance_after_transaction = self.account.balance
        return super().save()


class DepositForm(TransactionForm):
    def clean_amount(self):
        min_deposit_amount = 100
        amount = self.cleaned_data.get("amount")
        if amount < min_deposit_amount:
            raise forms.ValidationError(
                f"You need to deposit at least {min_deposit_amount} $"
            )

        return amount


class BorrowForm(TransactionForm):
    def clean_amount(self):
        account = self.account
        min_borrwing_amount = 1
        max_borrowing_amount = 1000
        balance = account.balance
        amount = self.cleaned_data.get("amount")
        if amount < min_borrwing_amount:
            raise forms.ValidationError(f"Please select a book to borrow.")

        if amount > max_borrowing_amount:
            raise forms.ValidationError(
                f"You can withdraw at most {max_borrowing_amount} $"
            )

        if amount > balance:
            raise forms.ValidationError(f"Insufficient funds to borrow this book.")

        return amount

transactions/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views.generic import CreateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Transaction
from .forms import DepositForm, BorrowForm
from .constants import DEPOSITE, BORROWING_BOOK
from django.contrib import messages
from django.http import HttpResponse
from datetime import datetime
from django.db.models import Sum
from django.shortcuts import get_object_or_404, redirect
from django.views import View
from django.urls import reverse_lazy
from accounts.models import UserLibraryAccount, BorrowingHistory
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.template.loader import render_to_string
from django.urls import reverse
from book.models import Book

# from django.conf import settings
# import stripe

# stripe.api_key = settings.STRIPE_SECRET_KEY


# Create your views here.


class TransactionCreateMixin(LoginRequiredMixin, CreateView):
    template_name = "transaction_form.html"
    model = Transaction
    title = ""
    success_url = reverse_lazy("transaction_report")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update(
            {
                "account": self.request.user.account,
            }
        )
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context.update(
            {
                "title": self.title,
            }
        )
        return context


class BorrowBookView(TransactionCreateMixin):
    form_class = DepositForm
    template_name = "transaction_form.html"
    title = "Purchase Book"

    def get_initial(self):
        initial = super().get_initial()
        book = get_object_or_404(Book, id=self.kwargs["id"])
        initial.update(
            {
                "transaction_type": BORROWING_BOOK,
                "amount": book.price,  # Set the initial amount to the book's price
            }
        )
        return initial

    def form_valid(self, form):
        amount = form.cleaned_data.get("amount")
        user = self.request.user
        account = user.account
        book = get_object_or_404(Book, id=self.kwargs["id"])

        # Update the user's account balance
        account.balance += amount
        account.save(update_fields=["balance"])

        # Create a transaction record
        Transaction.objects.create(
            account=account,
            amount=amount,
            book=book,
            balance_after_transaction=account.balance,
            transaction_type=BORROWING_BOOK,
        )

        messages.success(
            self.request, f"You have successfully borrowed a Book for {amount}$"
        )

        mail_subject = "Book Borrowing Confirmation"
        message = render_to_string(
            "deposite_mail.html", {"user": self.request.user, "amount": amount}
        )
        to_email = self.request.user.email
        send_email = EmailMultiAlternatives(mail_subject, "", to=[to_email])
        send_email.attach_alternative(message, "text/html")
        send_email.send()

        # Set a session variable to indicate form submission
        self.request.session["price_submitted"] = True

        # Redirect to the book details page
        book_id = self.kwargs["id"]
        return redirect(reverse("details_book", kwargs={"id": book_id}))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        book = get_object_or_404(Book, id=self.kwargs["id"])
        context["book"] = book
        context["title"] = self.title
        context["price_submitted"] = self.request.session.pop("price_submitted", False)
        return context

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     book = get_object_or_404(Book, id=self.kwargs["id"])
    #     context["key"] = settings.STRIPE_PUBLISHABLE_KEY
    #     context["book"] = book
    #     context["title"] = self.title
    #     context["price_submitted"] = self.request.session.pop("price_submitted", False)
    #     return context

    # def charge(request):
    #     if request.method == "POST":
    #         charge = stripe.Charge.create(
    #             amount=500,
    #             currency="usd",
    #             description="Payment Gatway",
    #             source=request.POST["stripeToken"],
    #         )
    #         return render(request, "charge.html")


class DepositeMoneyView(TransactionCreateMixin):
    form_class = DepositForm
    title = "Deposite"

    def get_initial(self):
        initial = {"transaction_type": DEPOSITE}
        return initial

    def form_valid(self, form):
        amount = form.cleaned_data.get("amount")
        account = self.request.user.account
        account.balance += amount
        account.save(update_fields=["balance"])

        messages.success(
            self.request, f"{amount}$ was deposited to your account successfully"
        )

        mail_subject = "Deposite Message"
        message = render_to_string(
            "deposite_mail.html", {"user": self.request.user, "amount": amount}
        )
        to_email = self.request.user.email
        send_email = EmailMultiAlternatives(mail_subject, "", to=[to_email])
        send_email.attach_alternative(message, "text/html")
        send_email.send()
        return super().form_valid(form)


class TransactionReportView(LoginRequiredMixin, ListView):
    template_name = "accounts/profile.html"
    model = Transaction
    context_object_name = "report_list"

    def get_queryset(self):
        queryset = super().get_queryset().filter(account=self.request.user.account)
        start_date_str = self.request.GET.get("start_date")
        end_date_str = self.request.GET.get("end_date")

        if start_date_str and end_date_str:
            start_date = datetime.strptime(start_date_str, "%Y-%m-%d").date()
            end_date = datetime.strptime(end_date_str, "%Y-%m-%d").date()

            queryset = queryset.filter(
                timestamp__date__gte=start_date, timestamp__date__lte=end_date
            )
            # Calculate balance
            self.balance = queryset.aggregate(Sum("amount"))["amount__sum"]
        else:
            self.balance = self.request.user.account.balance

        return queryset.distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["account"] = self.request.user.account
        context["balance"] = self.balance
        return context

transactions/templates/charge.html
{% extends 'base.html' %}
{% block head_title %}{{ title }}{% endblock %}
<br />
{% block body %}

<h1>Successfully paid</h1>

{% endblock %}

transactions/templates/deposite_mail.html
<h1>Hello {{user.first_name}} {{user.last_name}},</h1> 
<p>
  Your request for ${{amount}} has been successfully processed for borrowing a book. 
</p>
<p>Thanks for using our Library Services.</p>
<br>
<p>Sincerely,</p>
<p>The Library Management Team</p>

transactions/templates/transaction_form.html
{% extends 'base.html' %}
{% block head_title %}{{ title }}{% endblock %}
<br />
{% block body %}

<div style='height:100vh'>  
  <div class="w-full flex justify-center py-36 align-items-center">
  <div class="w-5/12 rounded-lg" style='background-color: #9BBEC8'>
    <h1 class="font-bold text-3xl text-center pb-5 pt-10 px-5">{{ title }}</h1>
    <form method="post" class="px-8 pt-6 pb-8 mb-4">
      {% csrf_token %}

      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
          Enter Book Price 
        </label>
        <input
          class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline"
          name="amount"
          id="amount"
          type="number"
          required
          placeholder="{{ book.price }}"
          value="{{ book.price }}" 
        />
      </div>
      {% if form.amount.errors %} {% for error in form.amount.errors %}
      <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
      {% endfor %} {% endif %}
      <div class="flex w-full justify-center">
        <button
          class="w-1/2 m-auto border border-blue-900 font-bold px-4 py-2 rounded-lg"
          type="submit"
          style="background-color:#164863; color: #DDF2FD;"
              onmouseover="this.style.backgroundColor='#DDF2FD'; this.style.color='#164863';"
              onmouseout="this.style.backgroundColor='#164863'; this.style.color='#DDF2FD';"
        >
          Submit
        </button>
      
      </div>
    </form> 
    
  </div>
  </div>

</div>
{% endblock %}

{% comment %} 
<form action={% url 'borrow_book' book.id %} method="post" class="px-8 pt-6 pb-8 mb-4"> {% endcomment %}
      {% comment %} {% csrf_token %} {% endcomment %}

      {% comment %} <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
          Enter Book Price 
        </label>
        <input
          class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline"
          name="amount"
          id="amount"
          type="number"
          required
          placeholder="{{ book.price }}"
          value="{{ book.price }}" 
        />
      </div>
      {% if form.amount.errors %} {% for error in form.amount.errors %}
      <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
      {% endfor %} {% endif %}
      <div class="flex w-full justify-center"> {% endcomment %}
          {% comment %} <h2>Buy for $5.00</h2>
  <script src='https://checkout.stripe.com/checkout.js' class='stripe-button'>
      data-key="{{key}}"
      data-description="Payment Gateway"
      data-amount="500"
      data-locale='auto'

  </script> 
      
      {% comment %} </div> 
    </form> {% endcomment %}

transactions/templates/transaction_report.html
{% comment %} {% extends 'base.html' %} {% load static %} {% load humanize %}
<br />
{% block head_title %} Transaction Details{% endblock %} {% block body %} {%
comment %}
<div class="my-10 py-3 px-4 bg-white rounded-xl shadow-md">
  <h1 class="font-bold text-3xl text-center pb-5 pt-2">Transaction Details</h1>
  <hr />
  <form method="get" action="{% url 'transaction_report' %}">
    <div class="flex justify-center">
      <div
        class="mt-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative w-4/12 mx-2"
      >
        <label for="start_date">From:</label>
        <input
          class="appearance-none w-full outline-none focus:outline-none active:outline-none"
          type="date"
          id="start_date"
          name="start_date"
        />
      </div>

      <div
        class="mt-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative w-4/12"
      >
        <label for="end_date">To:</label>
        <input
          class="appearance-none w-full outline-none focus:outline-none active:outline-none"
          type="date"
          id="end_date"
          name="end_date"
        />
      </div>
      <div
        class="mt-10 pl-3 pr-2 flex justify-between items-center relative w-4/12"
      >
        <button
          class="bg-blue-900 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
          type="submit"
        >
          Filter
        </button>
      </div>
    </div>
  </form>
  <table
    class="table-auto mx-auto w-full px-5 rounded-xl mt-8 border dark:border-neutral-500"
  >
    <thead class="bg-purple-900 text-white text-left">
      <tr
        class="bg-gradient-to-tr from-indigo-600 to-purple-600 rounded-md py-2 px-4 text-white font-bold"
      >
        <th class="px-4 py-2">Date</th>
        <th class="px-4 py-2">Transaction Type</th>
        <th class="px-4 py-2">Amount</th>
        <th class="px-4 py-2">Balance After Transaction</th>
      </tr>
    </thead>
    <tbody>
      {% for transaction in report_list %}
      <tr class="border-b dark:border-neutral-500">
        <td class="px-4 py-2">
          {{ transaction.timestamp|date:"F d, Y h:i A" }}
        </td>
        <td class="px-4 py-3 text-s border">
          <span
            class="px-2 py-1 font-bold leading-tight rounded-sm text-red-700 bg-red-100"
          >
            {{ transaction.get_transaction_type_display }}
          </span>
        </td>
        <td class="px-4 py-2">
          $ {{ transaction.amount|floatformat:2|intcomma }}
        </td>
        <td class="px-4 py-2">
          $ {{ transaction.balance_after_transaction|floatformat:2|intcomma }}
        </td>
      </tr>
      {% endfor %}
      <tr class="bg-gray-800 text-white">
        <th class="px-4 py-2 text-right" colspan="3">Current Balance</th>
        <th class="px-4 py-2 text-left">
          $ {{ account.balance|floatformat:2|intcomma }}
        </th>
      </tr>
    </tbody>
  </table>
</div>
{% endcomment %}